apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: bout-dev-ns
  name: dev-role
rules:
- apiGroups: ["", "apps"]
  resources: ["deployments", "pods"]
  verbs: ["list", "get", "create"]

---
# Role Binding 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: bout-dev-ns
  name: dev-role-binding
subjects:
- kind: User 
  name: maha 
  apiGroup: ""
roleRef:
  kind: Role
  name: dev-role
  apiGroup: ""
