# Taints and tolerations:
# bluepod
apiVersion: v1
kind: Pod
metadata:
  name: bluepod
spec:
  nodeSelector:
    color: blue
  containers:
    - image: nginx
      name: blue
  tolerations:
    - key: "color"
      operator: "Equal"
      value: "blue"
      effect: "NoSchedule"
---
apiVersion: v1
kind: Pod
metadata:
  name: greenpod
spec:
  nodeSelector:
    color: green
  containers:
    - image: nginx
      name: green
  tolerations:
    - key: "color"
      operator: "Equal"
      value: "green"
      effect: "NoSchedule"
---
apiVersion: v1
kind: Pod
metadata:
  name: orangepod
spec:
  nodeSelector:
    color: orange
  containers:
    - image: nginx
      name: orange
  tolerations:
    - key: "color"
      operator: "Equal"
      value: "orange"
      effect: "NoSchedule"
---
apiVersion: v1
kind: Pod
metadata:
  name: nocolorpod
spec:
  containers:
    - image: nginx
      name: nginx

---
# requiredDuringSchedulinIgnoredDuringExecution
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deploy
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 5
  template:
    metadata:
      labels:
        app: nginx 
    spec:
      nodeSelector:
        color: blue
      tolerations:
        - key: "color"
          operator: "Equal"
          value: "blue"
          effect: "NoSchedule"
      containers:
        - image: nginx
          name: nginx
          ports:
            - containerPort: 80
