apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:
  name: context-ingress
  annotations:
    kubernetes.io/ingress.class: "gce" #"gce-intenal" , "nginx" 
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: blue-service 
            port:
              number: 80

      
        