apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment 
  labels: 
    app: blue-app
spec:
  replicas: 1
  selector:
    matchLabels:
       app: blue-green-app
       color: blue 
  template:
    metadata:
      labels:
        app: blue-green-app
        color: blue # version 
    spec:
      containers: 
      - image: devopswithcloudhub/nginx:blue
        name: bluepod
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata:
  name: blue-green-service 
spec:
  type: NodePort
  selector: 
    app: blue-green-app
    color: blue # version 
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment 
  labels: 
    app: green-app
spec:
  replicas: 1
  selector:
    matchLabels:
       app: blue-green-app
       color: green 
  template:
    metadata:
      labels:
        app: blue-green-app
        color: green # version 
    spec:
      containers: 
      - image: devopswithcloudhub/nginx:green
        name: greenpod
        ports:
        - containerPort: 80