apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-deployment 
  labels: 
    app: main-deployment 
spec:
  replicas: 3
  selector:
    matchLabels:
       app: canary-test
       environment: main
  template:
    metadata:
      labels:
        app: canary-test
        environment: main
    spec:
      containers: 
      - image: devopswithcloudhub/nginx:blue
        name: bluepod
        ports:
        - containerPort: 80
---
# Orange deployment 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-deployment 
  labels: 
    app: canary-deployment 
spec:
  replicas: 1
  selector:
    matchLabels:
       app: canary-test
       environment: canary
  template:
    metadata:
      labels:
        app: canary-test
        environment: canary # version 
    spec:
      containers: 
      - image: devopswithcloudhub/nginx:orange
        name: orangepod
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata:
  name: canary-test-svc
spec:
  type: NodePort
  selector: 
    app: canary-test
  ports:
  - port: 80
    targetPort: 80