apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvvol
spec:
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 1Gi
    accessModes:
    - ReadWriteMany
  nfs:
    server: 34.57.240.42 # change to NFS Serve Public IP
    path: /opt/sfw
    readOnly: false


