apiVersion: v1
kind: ReplicationController
metadata:
  name: new-rc
spec:
  replicas: 2
  template:
    metadata:
      name: new-pod
      labels:
        env: dev
    spec:
      containers:
      - image: nginx
        name: nginximage

