apiVersion: v1
kind: Pod
metadata:
  name: ngnx-with-init
  labels:
    app: nginx-init
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  initContainers:
  - name: init-web-fetcher
    image: busybox 
    command:
    - wget
    - "-O"
    - "/shared/index.html"
    - "https://example.com"
    volumeMounts:
    - name: shared-data
      mountPath: /shared
  containers:
  - image: nginx 
    name: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html 

---
# service
apiVersion: v1
kind: Service 
metadata:
  name: nginx-svc
spec:
  type: NodePort
  selector:
    app: nginx-init
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
