# 1) Deployment using a single key from ConfigMap as env var
apiVersion: apps/v1
kind: Deployment
metadata:
  name: env-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: env-deploy
  template:
    metadata:
      labels:
        app: env-deploy
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ['sh', '-c', 'echo configmap is: $CONFIGMAPVAR && sleep 3600']
        env:
        - name: CONFIGMAPVAR
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: name
---
# 2) Deployment consuming entire ConfigMap via envFrom
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configmap-demo-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configmap-demo-deploy
  template:
    metadata:
      labels:
        app: configmap-demo-deploy
    spec:
      containers:
      - name: demo
        image: alpine
        command: ["sleep", "3600"]
        envFrom:
        - configMapRef:
            name: my-config
---
# 3) Deployment using both ConfigMap and Secret as env vars
apiVersion: apps/v1
kind: Deployment
metadata:
  name: env-with-secret-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: env-with-secret-deploy
  template:
    metadata:
      labels:
        app: env-with-secret-deploy
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ['sh', '-c', 'while true; do echo configmap is: $CONFIGMAPVAR and Secret is $SECRETVAR; sleep 10; done']
        env:
        - name: CONFIGMAPVAR
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: name
        - name: SECRETVAR
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: secret1
