# Deployment: reads keys via volume and prints them
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-configmap-vol-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-configmap-vol
  template:
    metadata:
      labels:
        app: my-configmap-vol
    spec:
      containers:
      - name: myapp-container
        image: busybox
        command: ["sh","-c","cat /config/name /config/Course; sleep 3600"]
        volumeMounts:
        - name: my-vol-cm
          mountPath: /config
      volumes:
      - name: my-vol-cm
        configMap:
          name: my-config