apiVersion: v1
kind: Pod
metadata:
  name: env-pod
spec:
  containers:
  - image: busybox
    name: busybox
    command: ['sh', '-c', 'while true; do sleep 10; done']
    volumeMounts:
    - name: configmap-volume
      mountPath: /k8s/config/configmap
    - name: secret-volume
      mountPath: /k8s/secret/secret
  volumes:
  - name: configmap-volume
    configMap:
      name: my-config
  - name: secret-volume
    secret:
      secretName: my-secret
---
apiVersion: v1
kind: Pod
metadata:
  name: my-configmap-pod
spec:
  containers:
  - name: myapp-container
    image: busybox
    command:
      - "sh"
      - "-c"
      - "echo Welcome $(MY_VAR) , your just joined $(MY_COURSE) && sleep 3600"
    env:
    - name: MY_VAR
      valueFrom:
        configMapKeyRef:
          name: my-config-map
          key: name
    - name: MY_COURSE
      valueFrom:
        configMapKeyRef:
          name: my-config-map
          key: Course
---
# Same example but with volume
apiVersion: v1
kind: Pod
metadata:
  name: my-configmap-pod-vol
spec:
  containers:
  - name: myapp-container
    image: busybox
    command:
      - "sh"
      - "-c"
      - "cat /config/name /config/Course"
    volumeMounts:
      - name: my-vol-cm
        mountPath: /config
  volumes:
    - name: my-vol-cm
      configMap:
        name: my-config
