apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
    - port: 3306

#This gives stable DNS:
   # mysql-0.mysql
#mysql-1.mysql
#mysql-2.mysql
