# First Example with configmaps
apiVersion: v1
kind: Pod
metadata:
  name: env-pod
spec:
  containers:
  - image: busybox
    name: busybox
    command: ['sh', '-c', 'echo configmap is: $CONFIGMAPVAR && sleep 3600']
    env:
      - name: CONFIGMAPVAR
        valueFrom:
          configMapKeyRef:
            name: my-config
            key: name

---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-pod
spec:
  containers:
    - name: demo
      image: alpine
      command: ["sleep", "3600"]
      envFrom: # when using envFrom , complete config map will be passed into cntainer. i.e., all the keys in the cm will be populated.
        - configMapRef:
            name: my-config 

---

apiVersion: v1
kind: Pod
metadata:
  name: env-pod
spec:
  containers:
  - image: busybox
    name: busybox
    command: ['sh', '-c', 'while true; do echo configmap is: $CONFIGMAPVAR and Secret is $SECRETVAR; sleep 10; done']
    # command: ['sh', '-c','echo Name is $CONFIGMAPVAR and Secret is $SECRETVAR && sleep 3600']

    env:
      - name: CONFIGMAPVAR
        valueFrom:
          configMapKeyRef:
            name: my-config
            key: name
      - name: SECRETVAR
        valueFrom:
          secretKeyRef:
            name: my-secret
            key: secret1